bin/setup, bin/check, rubocop fixes

diff --git a/bin/check b/bin/check
--- a/bin/check
+++ b/bin/check
@@ -80,20 +80,12 @@ if [ ! $? -eq 0 ]; then
 fi
 
 # for typescript
-
-tslint -c tslint.json app/assets/javascripts/**/*.ts
-if [ ! $? -eq 0 ]; then
-  echo 'tslint detected issues, commit aborted'
-  exit 1
-fi
-
-# for coffeescript
-
-coffeelint -f .coffeelint.json app/assets/javascripts/**/*.coffee
-if [ ! $? -eq 0 ]; then
-  echo 'coffeelint detected issues, commit aborted!'
-  exit 1
-fi
+#
+#tslint -c tslint.json app/assets/javascripts/**/*.ts
+#if [ ! $? -eq 0 ]; then
+#  echo 'tslint detected issues, commit aborted'
+#  exit 1
+#fi
 
 bundle exec brakeman -q -z --summary > /dev/null
 if [ ! $? -eq 0 ]; then
